{
 "title": "Hetzner Cloud Load Balancers",
 "description": "Dashboard for listing information about servers in the Hetzner Cloud using metrics from https://promhippie.github.io/hcloud_exporter/",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   {
    "name": "DS_PROMETHEUS",
    "query": "victoriametrics-metrics-datasource"
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(hcloud_loadbalancer_created_timestamp,cluster)"
    }
   },
   {
    "name": "loadbalancer",
    "label": "Load Balancer",
    "query": {
     "query": "label_values(hcloud_loadbalancer_created_timestamp{cluster=\"$cluster\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Targets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(hcloud_loadbalancer_targets_unhealthy{cluster=\"$cluster\", name=~\"$loadbalancer\"})",
     "legendFormat": "Unhealthy"
    },
    {
     "expr": "sum(hcloud_loadbalancer_targets_healthy{cluster=\"$cluster\", name=~\"$loadbalancer\"})",
     "legendFormat": "Healthy"
    },
    {
     "expr": "sum(hcloud_loadbalancer_max_targets{cluster=\"$cluster\", name=~\"$loadbalancer\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Services",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(hcloud_loadbalancer_services{cluster=\"$cluster\", name=~\"$loadbalancer\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(hcloud_loadbalancer_max_services{cluster=\"$cluster\", name=~\"$loadbalancer\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Certs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(hcloud_loadbalancer_assigned_certificates{cluster=\"$cluster\", name=~\"$loadbalancer\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(hcloud_loadbalancer_max_assigned_certificates{cluster=\"$cluster\", name=~\"$loadbalancer\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by (name) (hcloud_loadbalancer_open_connections{cluster=\"$cluster\", name=~\"$loadbalancer\"})",
     "legendFormat": "Open {{name}}"
    },
    {
     "expr": "sum by (name) (hcloud_loadbalancer_max_open_connections{cluster=\"$cluster\", name=~\"$loadbalancer\"})",
     "legendFormat": "Max {{name}}"
    }
   ]
  },
  {
   "title": "Connections per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (name) (hcloud_loadbalancer_connections_per_second{cluster=\"$cluster\", name=~\"$loadbalancer\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bandwith",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (name) (hcloud_loadbalancer_open_connections_bandwidth_in{cluster=\"$cluster\", name=~\"$loadbalancer\"})",
     "legendFormat": "Inbound {{name}}"
    },
    {
     "expr": "sum by (name) (hcloud_loadbalancer_open_connections_bandwidth_out{cluster=\"$cluster\", name=~\"$loadbalancer\"})",
     "legendFormat": "Outbound {{name}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (hcloud_loadbalancer_ingoing_traffic{cluster=\"$cluster\", name=~\"$loadbalancer\"})",
     "legendFormat": "Inbound {{name}}"
    },
    {
     "expr": "sum by (name) (hcloud_loadbalancer_outgoing_traffic{cluster=\"$cluster\", name=~\"$loadbalancer\"})",
     "legendFormat": "Outbound {{name}}"
    },
    {
     "expr": "sum by (name) (hcloud_loadbalancer_included_traffic{cluster=\"$cluster\", name=~\"$loadbalancer\"})",
     "legendFormat": "Included {{name}}"
    }
   ]
  }
 ]
}