{
 "title": "Hetzner Cloud Servers",
 "description": "Dashboard for listing information about servers in the Hetzner Cloud using metrics from https://promhippie.github.io/hcloud_exporter/",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   {
    "name": "DS_PROMETHEUS",
    "query": "victoriametrics-metrics-datasource"
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(hcloud_server_running,cluster)"
    }
   },
   {
    "name": "servers",
    "query": {
     "query": "label_values(hcloud_server_running{cluster=\"$cluster\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$servers Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "servers",
   "targets": [
    {}
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hcloud_server_running{cluster=\"$cluster\",name=~\"$servers\"}"
    }
   ]
  },
  {
   "title": "Memory Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hcloud_server_memory_bytes{cluster=\"$cluster\",name=~\"$servers\"}"
    }
   ]
  },
  {
   "title": "Incoming Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(hcloud_server_incoming_traffic_bytes{cluster=\"$cluster\",name=~\"$servers\"})",
     "legendFormat": "bytes transfered"
    }
   ]
  },
  {
   "title": "Outgoing Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(hcloud_server_outgoing_traffic_bytes{cluster=\"$cluster\",name=~\"$servers\"})",
     "legendFormat": "bytes transfered"
    }
   ]
  },
  {
   "title": "Disk Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hcloud_server_disk_bytes{cluster=\"$cluster\",name=~\"$servers\"}"
    }
   ]
  },
  {
   "title": "Backup Enabled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hcloud_server_backup{cluster=\"$cluster\",name=~\"$servers\"}"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hcloud_server_cores{cluster=\"$cluster\",name=~\"$servers\"}"
    }
   ]
  }
 ]
}