{
 "title": "CoreDNS with NodeLocalDNS",
 "description": "A dashboard for the CoreDNS DNS server which also exposes NodeLocal Cache  metrics.",
 "tags": [
  "dns",
  "coredns",
  "nodelocalcache"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "DS_PROMETHEUS",
    "query": "victoriametrics-metrics-datasource"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{k8s_app=\"node-local-dns\"}, instance)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(coredns_dns_requests_total,cluster)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(coredns_dns_requests_total,pod)"
    }
   },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "label_values(coredns_dns_requests_total,container)"
    }
   },
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "CoreDNS - Health Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{cluster=~\"$cluster\", pod=~\"$pod\",container=\"$container\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CoreDNS - CPU Usage by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{cluster=~\"$cluster\",pod=~\"$pod\",container=~\"$container\"}[5m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CoreDNS - Memory Usage by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{cluster=~\"$cluster\",pod=~\"$pod\",container=\"$container\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Requests (total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{cluster=\"$cluster\",pod=~\"$pod\",container=~\"$container\"}[5m])) by (proto)",
     "legendFormat": "{{proto}}"
    },
    {
     "expr": "sum(rate(coredns_dns_requests_total{cluster=\"$cluster\",pod=~\"$pod\",container=~\"$container\"}[5m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Requests (by qtype)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{cluster=\"$cluster\",pod=~\"$pod\",container=~\"$container\"}[5m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Requests (by zone)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{cluster=\"$cluster\",pod=~\"$pod\",container=~\"$container\"}[5m])) by (zone)",
     "legendFormat": "{{zone}}"
    },
    {
     "expr": "sum(rate(coredns_dns_requests_total{cluster=\"$cluster\",pod=~\"$pod\",container=~\"$container\"}[5m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Requests (by service)",
   "type": "timeseries",
   "description": "Total Requests by service on all nodes",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{cluster=\"$cluster\",pod=~\"$pod\",container=~\"$container\"}[5m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Requests (by pod)",
   "type": "timeseries",
   "description": "Requests by pod on all nodes",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{cluster=\"$cluster\",pod=~\"$pod\",container=~\"$container\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests (by zone, qtype)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{cluster=\"$cluster\",pod=~\"$pod\",container=~\"$container\"}[5m])) by (type, zone)",
     "legendFormat": "{{zone}} - {{type}}"
    },
    {
     "expr": "sum(rate(coredns_dns_requests_total{cluster=\"$cluster\",pod=~\"$pod\",container=~\"$container\"}[5m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Responses (duration)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket{cluster=\"$cluster\",pod=~\"$pod\",container=~\"$container\"}[5m])) by (le, job))",
     "legendFormat": "99% - {{ job }}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_duration_seconds_bucket{cluster=\"$cluster\",pod=~\"$pod\",container=~\"$container\"}[5m])) by (le, job))",
     "legendFormat": "90% - {{ job }}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_duration_seconds_bucket{cluster=\"$cluster\",pod=~\"$pod\",container=~\"$container\"}[5m])) by (le, job))",
     "legendFormat": "50% - {{ job }}"
    }
   ]
  },
  {
   "title": "CoreDNS - DNS request duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(increase(coredns_dns_request_duration_seconds_bucket{cluster=~\"$cluster\", pod=~\"$pod\", container=~\"$container\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Requests (size, udp)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_size_bytes_bucket{cluster=\"$cluster\",pod=~\"$pod\",container=~\"$container\",proto=\"udp\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}:99 "
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_size_bytes_bucket{cluster=\"$cluster\",pod=~\"$pod\",container=~\"$container\",proto=\"udp\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}:90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_size_bytes_bucket{cluster=\"$cluster\",pod=~\"$pod\",container=~\"$container\",proto=\"udp\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}:50"
    }
   ]
  },
  {
   "title": "Requests (size,tcp)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_size_bytes_bucket{cluster=\"$cluster\",pod=~\"$pod\",container=~\"$container\",proto=\"tcp\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}:99 "
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_size_bytes_bucket{cluster=\"$cluster\",pod=~\"$pod\",container=~\"$container\",proto=\"tcp\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}:90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_size_bytes_bucket{cluster=\"$cluster\",pod=~\"$pod\",container=~\"$container\",proto=\"tcp\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}:50"
    }
   ]
  },
  {
   "title": "Responses (size, udp)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_response_size_bytes_bucket{cluster=\"$cluster\",pod=~\"$pod\",container=~\"$container\",proto=\"udp\"}[5m])) by (le,proto)) ",
     "legendFormat": "{{proto}}:99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_response_size_bytes_bucket{cluster=\"$cluster\",pod=~\"$pod\",container=~\"$container\",proto=\"udp\"}[5m])) by (le,proto)) ",
     "legendFormat": "{{proto}}:90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_response_size_bytes_bucket{cluster=\"$cluster\",pod=~\"$pod\",container=~\"$container\",proto=\"udp\"}[5m])) by (le,proto)) ",
     "legendFormat": "{{proto}}:50%"
    }
   ]
  },
  {
   "title": "Responses (size, tcp)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_response_size_bytes_bucket{cluster=\"$cluster\",pod=~\"$pod\",container=~\"$container\",proto=\"tcp\"}[5m])) by (le,proto)) ",
     "legendFormat": "{{proto}}:99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_response_size_bytes_bucket{cluster=\"$cluster\",pod=~\"$pod\",container=~\"$container\",proto=\"tcp\"}[5m])) by (le,proto)) ",
     "legendFormat": "{{proto}}:90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_response_size_bytes_bucket{cluster=\"$cluster\",pod=~\"$pod\",container=~\"$container\",proto=\"tcp\"}[5m])) by (le, proto)) ",
     "legendFormat": "{{proto}}:50%"
    }
   ]
  },
  {
   "title": "Responses (by rcode)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_responses_total{cluster=\"$cluster\",pod=~\"$pod\",container=~\"$container\"}[5m])) by (rcode)",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "Responses (by rcode,zone)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_responses_total{cluster=\"$cluster\",pod=~\"$pod\",container=~\"$container\"}[5m])) by (rcode,zone)",
     "legendFormat": "{{rcode}} {{zone}}"
    }
   ]
  },
  {
   "title": "Cache (size)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(coredns_cache_entries{cluster=\"$cluster\",pod=~\"$pod\",container=~\"$container\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cache (hitrate)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{cluster=\"$cluster\",pod=~\"$pod\",container=~\"$container\"}[5m])) by (type)",
     "legendFormat": "hits:{{type}}"
    },
    {
     "expr": "sum(rate(coredns_cache_misses_total{cluster=\"$cluster\",pod=~\"$pod\",container=~\"$container\"}[5m])) by (type)",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Requests (DO bit)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_do_requests_total{cluster=\"$cluster\",pod=~\"$pod\",container=~\"$container\"}[5m]))",
     "legendFormat": "DO"
    },
    {
     "expr": "sum(rate(coredns_dns_requests_total{cluster=\"$cluster\",pod=~\"$pod\",container=~\"$container\"}[5m]))",
     "legendFormat": "total"
    }
   ]
  }
 ]
}