# Global options
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
commonAnnotations:
  grafana_folder: "Kubernetes"
#namespace: monitoring

# Generate a ConfigMap for each dashboard
configMapGenerator:

#################################################
# Views Dashboards
#################################################

- name: dashboards-k8s-views-global
  files: [ dashboards/kubernetes/global.json ]

- name: dashboards-k8s-views-namespaces
  files: [ dashboards/kubernetes/namespaces.json ]

- name: dashboards-k8s-views-nodes
  files: [ dashboards/kubernetes/nodes.json ]

- name: dashboards-k8s-views-pods
  files: [ dashboards/kubernetes/pods.json ]

#################################################
# System / Addons Dashboards
#################################################

- name: dashboards-k8s-system-api-server
  files: [ dashboards/kubernetes/api-server.json ]

- name: dashboards-k8s-system-coredns
  files: [ dashboards/kubernetes/coredns.json ]

- name: dashboards-k8s-addons-prometheus
  files: [ dashboards/k8s-addons-prometheus.json ]

- name: dashboards-k8s-addons-trivy-operator
  files: [ dashboards/k8s-addons-trivy-operator.json ]
