{
 "title": "Graylog",
 "description": "Prometheus Graylog exporter metrics.",
 "tags": [
  "prometheus",
  "graylog"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "DS_PROMETHEUS",
    "query": "victoriametrics-metrics-datasource"
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(gl_journal_size,cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(gl_journal_size{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(gl_journal_size{service=\"graylog\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Journal utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gl_journal_utilization_ratio{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Journal size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(gl_journal_size{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(gl_journal_size_limit{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{area=\"heap\",cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_bytes_init{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Thread counts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(jvm_threads_current{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "Buffers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Input Buffer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(gl_buffer_usage{type=\"input\",cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(gl_buffer_size{type=\"input\",cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Process Buffer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(gl_buffer_usage{type=\"process\",cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(gl_buffer_size{type=\"input\",cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Output Buffer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(gl_buffer_usage{type=\"output\",cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(gl_buffer_size{type=\"output\",cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Messages received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(sum(gl_input_incoming_messages_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[1m]))",
     "legendFormat": "Input"
    },
    {
     "expr": "rate(sum(gl_stream_incoming_messages_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"})[1m])",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Messages appended to disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(sum(gl_kafka_journal_written_messages_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[1m]))",
     "legendFormat": "append"
    }
   ]
  }
 ]
}