{
 "title": "PHP-FPM",
 "description": "A companion dashboard for https://github.com/hipages/php-fpm_exporter\r\n\r\nThe dashboard caters to Kubernetes & PHP-FPM but can be easily adjusted.",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "DS_PROMETHEUS",
    "query": "victoriametrics-metrics-datasource"
   },
   {
    "name": "cluster",
    "label": "Namespace",
    "query": {
     "query": "label_values(phpfpm_up,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(phpfpm_up{cluster=~\"$cluster\"},namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(phpfpm_up{cluster=~\"$cluster\", namespace=~\"$namespace\"},service)"
    }
   },
   {
    "name": "pool",
    "query": {
     "query": "label_values(phpfpm_up{cluster=~\"$cluster\", namespace=~\"$namespace\", service=\"$service\"},pool)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values({cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$service-.*\"},container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Process Utilisation",
   "type": "gauge",
   "description": "Utilisation of processes based on active/inactive processes",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(phpfpm_active_processes{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", pool=~\"$pool\"}\n) by(pool)\n  /\nsum( phpfpm_total_processes{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", pool=~\"$pool\"}\n) by(pool) * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Max Children reached",
   "type": "stat",
   "description": "How many times was the maximum amount of children reached?",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(phpfpm_max_children_reached{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", pool=~\"$pool\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Accepted connections (rpm)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(phpfpm_accepted_connections{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", pool=~\"$pool\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# of pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(phpfpm_up{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", pool=~\"$pool\"} > 0)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Queued Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(phpfpm_listen_queue{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", pool=~\"$pool\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Scrape failures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(phpfpm_scrape_failures{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", pool=~\"$pool\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# of processes by state",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(phpfpm_process_state{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", pool=~\"$pool\"}) by (state)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{state}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(phpfpm_process_state{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", pool=~\"$pool\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Request Duration by process",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(phpfpm_process_request_duration{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", pool=~\"$pool\"}) by (pid_hash)",
     "legendFormat": "{{pid_hash}}",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Queued requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(phpfpm_listen_queue{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", pool=~\"$pool\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "# of requests",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requests per process",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(phpfpm_process_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", pool=~\"$pool\"}) by (pid_hash)",
     "legendFormat": "{{pid_hash}}",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "# of Active & Idle processes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(phpfpm_active_processes{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", pool=~\"$pool\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "# of active processes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(phpfpm_idle_processes{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", pool=~\"$pool\"})",
     "legendFormat": "# of idle processes"
    },
    {
     "expr": "sum(phpfpm_total_processes{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", pool=~\"$pool\"})",
     "legendFormat": "# of total processes"
    }
   ]
  },
  {
   "title": "Total process utilisation & container termination",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg((sum(phpfpm_active_processes{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", pool=~\"$pool\"}) by (kubernetes_pod_name) *100) / sum(phpfpm_total_processes{cluster=~\"$cluster\", namespace=~\"$namespace\", service=~\"$service\", pool=~\"$pool\"}) by (kubernetes_pod_name))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Process utilisation",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(kube_pod_container_status_terminated{pod=~\"static-thread-handling-.*\"})",
     "legendFormat": "# of pod terminations"
    }
   ]
  },
  {
   "title": "# of pods in a ReplicaSet",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_replicaset_spec_replicas{cluster=~\"$cluster\", namespace=~\"$namespace\", replicaset=~\"$service-.*\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{replicaset}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of pods",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count(container_memory_usage_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$service-.*\"}) by (pod))",
     "legendFormat": "pods"
    },
    {
     "expr": "count(count(container_memory_usage_bytes{pod_name=~\"$branch-.*\", namespace=\"$namespace\"}) by (kubernetes_io_hostname))",
     "legendFormat": "hosts"
    }
   ]
  },
  {
   "title": "Cpu usage (relative to limit)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"$service-.*\",container=~\"$container\", namespace=~\"$namespace\"}[30s])) by (namespace,container) / sum(container_spec_cpu_quota{pod=~\"$service-.*\",container=~\"$container\", namespace=~\"$namespace\"} / container_spec_cpu_period{container=~\"$container\", namespace=~\"$namespace\"}) by (namespace,container)",
     "legendFormat": "actual"
    }
   ]
  },
  {
   "title": "Memory usage (relative to limit)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"$service-.*\",container=~\"$container\", namespace=~\"$namespace\"}) by (namespace,container) / sum(container_spec_memory_limit_bytes{pod=~\"$service-.*\",container=~\"$container\", namespace=~\"$namespace\"}) by (namespace,container)",
     "legendFormat": "actual"
    }
   ]
  },
  {
   "title": "CPU usage per pod (relative to limit)",
   "type": "timeseries",
   "description": "The metric may not work if there is no quota assigned.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  irate(\n    container_cpu_usage_seconds_total{pod=~\"$service-.*\",container=~\"$container\", namespace=~\"$namespace\"}[1m]\n  )\n) by (namespace,container,pod) /\nsum(\n  container_spec_cpu_quota{pod=~\"$service-.*\",container=~\"$container\", namespace=~\"$namespace\"} /\n  container_spec_cpu_period{pod=~\"$service-.*\",container=~\"$container\", namespace=~\"$namespace\"}\n) by (namespace,container,pod)",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Memory usage per pod (relative to limit)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"$service-.*\",container=~\"$container\", namespace=~\"$namespace\"}) by (namespace,container,pod) / sum(container_spec_memory_limit_bytes{pod=~\"$service-.*\",container=~\"$container\", namespace=~\"$namespace\"}) by (namespace,container,pod)",
     "legendFormat": "{{pod}}",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Cpu usage (per pod)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"$service-.*\",container=~\"$container\", namespace=~\"$namespace\"}[30s])) by (id,pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(container_spec_cpu_quota{pod=~\"$service-.*\",container=~\"$container\", namespace=~\"$namespace\"} / container_spec_cpu_period{pod=~\"$service-.*\",container=~\"$container\", namespace=~\"$namespace\"}) by (namespace,container) / count(container_memory_usage_bytes{pod=~\"$service-.*\",container=~\"$container\", namespace=~\"$namespace\"}) by (namespace,container) ",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(container_spec_cpu_shares{pod=~\"$service-.*\",container=~\"$container\", namespace=~\"$namespace\"} / 1024) by (namespace,container) / count(container_spec_cpu_shares{pod=~\"$service-.*\",container=~\"$container\", namespace=~\"$namespace\"}) by (namespace,container) ",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory usage (avg per pod)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"$service-.*\",container=~\"$container\", namespace=~\"$namespace\"}) by (namespace,container) / count(container_memory_usage_bytes{pod=~\"$service-.*\",container=~\"$container\", namespace=~\"$namespace\"}) by (namespace,container) ",
     "legendFormat": "actual"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod=~\"$service-.*\",container=~\"$container\", namespace=~\"$namespace\"}) by (namespace,container) / count(container_memory_usage_bytes{pod=~\"$service-.*\",container=~\"$container\", namespace=~\"$namespace\"}) by (namespace,container) ",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Cpu usage (total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"$service-.*\",container=~\"$container\", namespace=~\"$namespace\"}[30s])) by (namespace,container)",
     "legendFormat": "actual"
    },
    {
     "expr": "sum(container_spec_cpu_quota{pod=~\"$service-.*\",container=~\"$container\", namespace=~\"$namespace\"} / container_spec_cpu_period{pod=~\"$service-.*\",container=~\"$container\", namespace=~\"$namespace\"}) by (namespace,container)",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(container_spec_cpu_shares{pod=~\"$service-.*\",container=~\"$container\", namespace=~\"$namespace\"} / 1024) by (namespace,container) ",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory usage (total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"$service-.*\",container=~\"$container\", namespace=~\"$namespace\"}) by (namespace,container)",
     "legendFormat": "actual"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod=~\"$service-.*\",container=~\"$container\", namespace=~\"$namespace\"}) by (namespace,container)",
     "legendFormat": "limit"
    }
   ]
  }
 ]
}