{
 "title": "Solr Dashboard",
 "description": "Default dashboard for Solr Exporter",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "DS_PROMETHEUS",
    "query": "victoriametrics-metrics-datasource"
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(solr_ping,cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(solr_ping{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "zk_host",
    "query": {
     "query": "label_values(solr_ping{cluster=~\"$cluster\", namespace=~\"$namespace\"},zk_host)"
    }
   },
   {
    "name": "base_url",
    "query": {
     "query": "label_values(solr_ping{cluster=~\"$cluster\", namespace=~\"$namespace\"},base_url)"
    }
   },
   {
    "name": "collection",
    "query": {
     "query": "label_values(solr_collections_shard_state{zk_host=~\"$zk_host\", collection=~\".+\", cluster=~\"$cluster\", namespace=~\"$namespace\"},collection)"
    }
   },
   {
    "name": "shard",
    "query": {
     "query": "label_values(solr_collections_shard_state{zk_host=~\"$zk_host\", collection=~\"$collection\", shard=~\".+\", cluster=~\"$cluster\", namespace=~\"$namespace\"},shard)"
    }
   },
   {
    "name": "replica",
    "query": {
     "query": "label_values(solr_collections_replica_state{zk_host=~\"$zk_host\", collection=~\"$collection\", shard=~\"$shard\", replica=~\".+\", cluster=~\"$cluster\", namespace=~\"$namespace\"},replica)"
    }
   },
   {
    "name": "core",
    "query": {
     "query": "label_values(solr_collections_replica_state{zk_host=~\"$zk_host\", collection=~\"$collection\", shard=~\"$shard\", replica=~\"$replica\", cluster=~\"$cluster\", namespace=~\"$namespace\"},core)"
    }
   },
   {
    "name": "searchHandler",
    "query": {
     "query": "label_values(solr_metrics_core_query_errors_1minRate{zk_host=~\"$zk_host\", collection=~\"$collection\", shard=~\"$shard\", replica=~\"$replica\", cluster=~\"$cluster\", namespace=~\"$namespace\"},searchHandler)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Solr Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number of live nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "solr_collections_live_nodes{cluster=~\"$cluster\",namespace=~\"$namespace\"}",
       "legendFormat": "Live nodes"
      },
      {
       "expr": "count(count by (node_name) (solr_collections_replica_state{cluster=~\"$cluster\",namespace=~\"$namespace\"})) < solr_collections_live_nodes{cluster=~\"$cluster\",namespace=~\"$namespace\"} or solr_collections_live_nodes{cluster=~\"$cluster\",namespace=~\"$namespace\"}",
       "legendFormat": "Total nodes"
      }
     ]
    },
    {
     "title": "Zookeepers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(solr_zookeeper_nodestatus{cluster=~\"$cluster\",namespace=~\"$namespace\"} == 1)",
       "legendFormat": "Healthy nodes"
      },
      {
       "expr": "solr_zookeeper_ensemble_size{cluster=~\"$cluster\",namespace=~\"$namespace\"}",
       "legendFormat": "Ensemble size"
      }
     ]
    },
    {
     "title": "Shard leaders",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "solr_collections_shard_leader{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}",
       "legendFormat": "{{collection}} {{shard}} {{replica}} ({{node_name}})"
      }
     ]
    },
    {
     "title": "Number of collections",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count by (collection) (solr_collections_replica_state{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}))"
      }
     ]
    },
    {
     "title": "Current replica state",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 9, "x": 3, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(solr_collections_replica_state{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"})",
       "legendFormat": "Total replicas"
      },
      {
       "expr": "count(solr_collections_replica_state{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"} == 1) OR on() vector(0)",
       "legendFormat": "Active"
      },
      {
       "expr": "count(solr_collections_replica_state{cluster=~\"$cluster\",namespace=~\"$namespace\",state=\"down\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}) OR on() vector(0)",
       "legendFormat": "Down"
      },
      {
       "expr": "count(solr_collections_replica_state{cluster=~\"$cluster\",namespace=~\"$namespace\",state=\"recovering\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}) OR on() vector(0)",
       "legendFormat": "Recovering"
      },
      {
       "expr": "count(solr_collections_replica_state{cluster=~\"$cluster\",namespace=~\"$namespace\",state=\"recovery_failed\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}) OR on() vector(0)",
       "legendFormat": "Recovery failed"
      }
     ]
    },
    {
     "title": "Replica state history",
     "type": "timeseries",
     "description": "Active replicas have value 0. Non-active replicas will show stacked in the graph.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "1 - solr_collections_replica_state{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}",
       "legendFormat": "{{collection}} {{shard}} {{replica}} ({{node_name}})={{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total QPS (by collection)",
     "type": "timeseries",
     "description": "Distributed QPS 1-min rate  aggregated by collection, roughly the current QPS across all nodes per collection",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (collection) (solr_metrics_core_query_1minRate{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"})",
       "legendFormat": "{{collection}}"
      }
     ]
    },
    {
     "title": "Total QPS (by node)",
     "type": "timeseries",
     "description": "Distributed QPS 1-min rate aggregated by base_url (Solr node)",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (base_url) (solr_metrics_core_query_1minRate{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"})",
       "legendFormat": "{{base_url}}"
      }
     ]
    },
    {
     "title": "Distributed Query Time per Core (p95 ms)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "solr_metrics_core_query_p95_ms{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"}",
       "legendFormat": "{{base_url}}  {{core}}  {{searchHandler}}"
      }
     ]
    },
    {
     "title": "Distributed QPS per Core (5-min rate)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "solr_metrics_core_query_5minRate{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"}",
       "legendFormat": "{{base_url}}  {{core}}  {{searchHandler}}"
      }
     ]
    },
    {
     "title": "Distributed Query Time per Core (p99 ms)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "solr_metrics_core_query_p99_ms{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"}",
       "legendFormat": "{{base_url}}  {{core}}  {{searchHandler}}"
      }
     ]
    },
    {
     "title": "Distributed QPS per Core (1-min rate)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "solr_metrics_core_query_1minRate{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"}",
       "legendFormat": "{{base_url}}  {{core}}  {{searchHandler}}"
      }
     ]
    },
    {
     "title": "Distributed Query Time per Core (p75 ms)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "solr_metrics_core_query_p75_ms{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"}",
       "legendFormat": "{{base_url}}  {{core}}  {{searchHandler}}"
      }
     ]
    },
    {
     "title": "Local Query Count per Core",
     "type": "timeseries",
     "description": "Helps identify if a core is receiving more traffic than other cores, possibly indicating unbalanced load.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(solr_metrics_core_query_local_count{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"}[1m])",
       "legendFormat": "{{base_url}}/{{core}}{{searchHandler}}"
      }
     ]
    },
    {
     "title": "Local QPS per Core (1-min rate)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "solr_metrics_core_query_local_1minRate{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"}",
       "legendFormat": "{{base_url}}/{{core}}{{searchHandler}}"
      }
     ]
    },
    {
     "title": "Local Query Time per Core (p95 ms)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "solr_metrics_core_query_local_p95_ms{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"}",
       "legendFormat": "{{base_url}}/{{core}}{{searchHandler}}"
      }
     ]
    },
    {
     "title": "Query Client Errors per Core (1-min rate)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "solr_metrics_core_query_client_errors_1minRate{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"}",
       "legendFormat": "{{base_url}}  {{core}}  {{searchHandler}}"
      }
     ]
    },
    {
     "title": "Query Errors per Core (1-min rate)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "solr_metrics_core_query_errors_1minRate{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"}",
       "legendFormat": "{{base_url}}  {{core}}  {{searchHandler}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Jetty Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Requests",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(solr_metrics_jetty_requests_total{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\"}[1m])",
       "legendFormat": "{{base_url}} {{method}}"
      }
     ]
    },
    {
     "title": "Response",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(solr_metrics_jetty_response_total{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\"}[1m])",
       "legendFormat": "{{base_url}} {{status}}"
      }
     ]
    },
    {
     "title": "Dispatches",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(solr_metrics_jetty_dispatches_total{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\"}[1m])",
       "legendFormat": "{{base_url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Buffers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "solr_metrics_jvm_buffers{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{pool}}"
      }
     ]
    },
    {
     "title": "Buffer Size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "solr_metrics_jvm_buffers_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{pool}} {{item}}"
      }
     ]
    },
    {
     "title": "GC Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(solr_metrics_jvm_gc_total{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\"}[1m])",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "GC Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(solr_metrics_jvm_gc_seconds_total{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\"}[1m])",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "Heap Size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "solr_metrics_jvm_memory_heap_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "Non-Heap Size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "solr_metrics_jvm_memory_non_heap_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "Pool Size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "solr_metrics_jvm_memory_pools_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{space}} {{item}}"
      }
     ]
    },
    {
     "title": "Memory Size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "solr_metrics_jvm_memory_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "solr_metrics_jvm_threads{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    }
   ]
  },
  {
   "title": "OS Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "solr_metrics_jvm_os_memory_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "solr_metrics_jvm_os_file_descriptors{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "CPU Load",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "solr_metrics_jvm_os_cpu_load{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "CPU Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(solr_metrics_jvm_os_cpu_time_seconds{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\"}[1m])",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "solr_metrics_jvm_os_load_average{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Requests",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "solr_metrics_node_requests_total{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{handler}}"
      }
     ]
    },
    {
     "title": "Request Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(solr_metrics_node_time_seconds_total{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\"}[1m])",
       "legendFormat": "{{base_url}}{{handler}}"
      }
     ]
    },
    {
     "title": "Client Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(solr_metrics_node_client_errors_total{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\"}[1m])",
       "legendFormat": "{{base_url}}{{handler}}"
      }
     ]
    },
    {
     "title": "Server Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(solr_metrics_node_server_errors_total{cluster=~\"$cluster\",namespace=\"$namespace\",base_url=~\"$base_url\"}[1m])",
       "legendFormat": "{{base_url}}{{handler}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(solr_metrics_node_errors_total{cluster=~\"$cluster\",namespace=\"$namespace\",base_url=~\"$base_url\"}[1m])",
       "legendFormat": "{{base_url}}{{handler}}"
      }
     ]
    },
    {
     "title": "Timeouts",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(solr_metrics_node_timeouts_total{cluster=~\"$cluster\",namespace=\"$namespace\",base_url=~\"$base_url\"}[1m])",
       "legendFormat": "{{base_url}}{{handler}}"
      }
     ]
    },
    {
     "title": "Cores",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "solr_metrics_node_cores{cluster=~\"$cluster\",namespace=\"$namespace\",base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "Core Root File System",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "solr_metrics_node_core_root_fs_bytes{cluster=~\"$cluster\",namespace=\"$namespace\",base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "Thread Pool Completed",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "solr_metrics_node_thread_pool_completed_total{cluster=~\"$cluster\",namespace=\"$namespace\",base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{handler}} {{executor}}"
      }
     ]
    },
    {
     "title": "Thread Pool Submitted",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "solr_metrics_node_thread_pool_submitted_total{cluster=~\"$cluster\",namespace=\"$namespace\",base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{handler}} {{executor}}"
      }
     ]
    },
    {
     "title": "Thread Pool Running",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "solr_metrics_node_thread_pool_running{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{handler}} {{executor}}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "solr_metrics_node_connections{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{handler}} {{item}}"
      }
     ]
    },
    {
     "title": "Leader Count (by node)",
     "type": "timeseries",
     "description": "Number of leaders on each node",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (base_url) (solr_collections_shard_leader{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"})",
       "legendFormat": "{{base_url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Core Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(solr_metrics_core_requests_total{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}}"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(solr_metrics_core_time_seconds_total{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}}"
    }
   ]
  },
  {
   "title": "Client Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(solr_metrics_core_client_errors_total{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}}"
    }
   ]
  },
  {
   "title": "Server Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(solr_metrics_core_server_errors_total{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(solr_metrics_core_errors_total{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}}"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(solr_metrics_core_timeouts_total{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}}"
    }
   ]
  },
  {
   "title": "Searcher Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "solr_metrics_core_searcher_cache_ratio{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}",
     "legendFormat": "{{base_url}}/{{core}} {{type}} {{item}}"
    }
   ]
  },
  {
   "title": "Searcher Cache",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "solr_metrics_core_searcher_cache{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}",
     "legendFormat": "{{base_url}}/{{core}} {{type}} {{item}}"
    }
   ]
  },
  {
   "title": "Searcher Warm Up Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "solr_metrics_core_searcher_warmup_time_seconds{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}",
     "legendFormat": "{{base_url}}/{{core}} {{type}}"
    }
   ]
  },
  {
   "title": "Searcher Cumulative Cache",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(solr_metrics_core_searcher_cumulative_cache_total{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}} {{type}} {{item}}"
    }
   ]
  },
  {
   "title": "File System",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "solr_metrics_core_fs_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Index Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "solr_metrics_core_index_size_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Searcher Documents",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "solr_metrics_core_searcher_documents{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}",
     "legendFormat": "{{base_url}}/{{core}} {{item}}"
    }
   ]
  },
  {
   "title": "Update Handler Adds (cumulative)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_adds_total{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Pending Docs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "solr_metrics_core_update_handler_pending_docs{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Deletes By ID",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_deletes_by_id_total{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Deletes By Query",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_deletes_by_query_total{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Expunge Deletes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_expunge_deletes_total{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Merges",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_merges_total{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Splits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_splits_total{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Optimizes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_optimizes_total{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Rollbacks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_rollbacks_total{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Soft Auto Commits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_soft_auto_commits_total{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Auto Commits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_auto_commits_total{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Commits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_commits_total{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_errors_total{cluster=~\"$cluster\",namespace=~\"$namespace\",base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  }
 ]
}