{
 "title": "ARC Autoscaling Runner Set Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "DS_PROMETHEUS",
    "query": "victoriametrics-metrics-datasource"
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(gha_desired_runners,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "ARC System Namespace",
    "query": {
     "query": "label_values(gha_desired_runners{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "Scaleset",
    "label": "Scale Set",
    "query": {
     "query": "label_values(gha_desired_runners{cluster=\"$cluster\"},scaleset)"
    }
   },
   {
    "name": "organisation",
    "query": {
     "query": "label_values(gha_job_startup_duration_seconds_sum{cluster=\"$cluster\"},organization)"
    }
   },
   {
    "name": "repository",
    "query": {
     "query": "label_values(gha_job_startup_duration_seconds_sum{cluster=\"$cluster\"},repository)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Job Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Startup Duration",
   "type": "heatmap",
   "description": "Heat map showing the typical time before a job starts and whether the number of jobs in that time bucket are increasing or decreasing.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(le) (increase(gha_job_startup_duration_seconds_bucket{cluster=\"$cluster\", scaleset=~\"$Scaleset\", namespace=~\"$namespace\", organization=~\"$organisation\", repository=~\"$repository\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Job Execution",
   "type": "heatmap",
   "description": "Heat map showing the typical time to complete a job and whether the number of jobs in that time bucket are increasing or decreasing.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(le) (increase(gha_job_execution_duration_seconds_bucket{cluster=\"$cluster\", scaleset=~\"$Scaleset\", namespace=~\"$namespace\", organization=~\"$organisation\", repository=~\"$repository\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Job time spent",
   "type": "timeseries",
   "description": "The number of jobs assigned to the scale set.  The threshold is triggered with the number of assigned jobs exceeds the number of desired runners. This indicates that not all jobs will have an available runner.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(gha_job_execution_duration_seconds_sum{cluster=\"$cluster\", namespace=~\"$namespace\", scaleset=~\"$Scaleset\", organization=~\"$organisation\", repository=~\"$repository\"}[5m])\n/\nrate(gha_job_execution_duration_seconds_count{cluster=\"$cluster\", namespace=~\"$namespace\", scaleset=~\"$Scaleset\", organization=~\"$organisation\", repository=~\"$repository\"}[5m])) by (organization, repository)",
     "legendFormat": "{{organization}}/{{repository}}"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "timeseries",
   "description": "The number of jobs assigned to the scale set.  The threshold is triggered with the number of assigned jobs exceeds the number of desired runners. This indicates that not all jobs will have an available runner.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(gha_assigned_jobs{cluster=\"$cluster\", namespace=~\"$namespace\", scaleset=~\"$Scaleset\", organization=~\"$organisation\"})",
     "legendFormat": "Assigned"
    },
    {
     "expr": "sum(gha_running_jobs{cluster=\"$cluster\", namespace=~\"$namespace\", scaleset=~\"$Scaleset\", organization=~\"$organisation\"})",
     "legendFormat": "Running"
    }
   ]
  },
  { "title": "Runner Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Runners",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "gha_min_runners{cluster=\"$cluster\", organization=~\"$organisation\", scaleset=~\"$Scaleset\"}",
     "legendFormat": "Min"
    },
    {
     "expr": "gha_max_runners{cluster=\"$cluster\", organization=~\"$organisation\", scaleset=~\"$Scaleset\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "gha_desired_runners{cluster=\"$cluster\", organization=~\"$organisation\", scaleset=~\"$Scaleset\"}",
     "legendFormat": "Desired"
    },
    {
     "expr": "gha_idle_runners{cluster=\"$cluster\", organization=~\"$organisation\", scaleset=~\"$Scaleset\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "gha_registered_runners{cluster=\"$cluster\", organization=~\"$organisation\", scaleset=~\"$Scaleset\"}",
     "legendFormat": "Registered"
    },
    {
     "expr": "gha_busy_runners{cluster=\"$cluster\", organization=~\"$organisation\", scaleset=~\"$Scaleset\"}",
     "legendFormat": "Busy"
    }
   ]
  },
  {
   "title": "Container Pod Status",
   "type": "timeseries",
   "description": "The Kubernetes-reported pod status.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{cluster=\"$cluster\", namespace=~\"$namespace\"}) != 0 or vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting{cluster=\"$cluster\", namespace=~\"$namespace\"}) != 0 or vector(0)",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated_reason{namespace=~\"$namespace\", reason=\"Completed\"}) != 0 or vector(0)",
     "legendFormat": "Completed"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated_reason{namespace=~\"$namespace\", reason=\"Error\"}) != 0 or vector(0)",
     "legendFormat": "Error"
    },
    { "expr": "sum(gha_desired_runners)+1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Peak Container Memory",
   "type": "timeseries",
   "description": "The peak memory used by a container in a given scale set's namespace.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", container!=\"\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container I/O",
   "type": "timeseries",
   "description": "The sum of the reads and writes occurring within the runner namespace.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{cluster=\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) > 0 or vector(0)",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{cluster=\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) > 0 or vector(0)",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Out of Memory",
   "type": "timeseries",
   "description": "The number of containers that are reporting that they were terminated by an out-of-memory condition (OOMK.iller)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_last_terminated_reason{cluster=\"$cluster\", reason=\"OOMKilled\",namespace=~\"$namespace\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "description": "The time required by Prometheus to read and process metrics. Long scrape times can delay metrics updates or lead to metrics loss. Increasing time often indicates issues with metrics cardinality or cluster resources.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (job) (scrape_duration_seconds{cluster=\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}