{
 "title": "OpenSearch",
 "description": "This dashboard is the result of the build of the mixin dashboards published by the OpenSearch Prometheus Exporter plugin by Aiven (https://github.com/Aiven-Open/prometheus-exporter-plugin-for-opensearch/tree/mixin)",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "DS_PROMETHEUS",
    "label": "DS_PROMETHEUS",
    "query": "victoriametrics-metrics-datasource"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(opensearch_cluster_status,cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(opensearch_jvm_uptime_seconds{cluster=~\"$cluster\"},node)"
    }
   },
   {
    "name": "shard_type",
    "label": "Shard",
    "query": {
     "query": "label_values(opensearch_cluster_shards_number{cluster=~\"$cluster\"},type)"
    }
   },
   {
    "name": "pool_name",
    "label": "Threadpool Type name",
    "query": {
     "query": "label_values(opensearch_threadpool_tasks_number{cluster=~\"$cluster\"},name)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "15s, 30s, 1m, 5m, 1h, 6h, 1d" }
  ]
 },
 "panels": [
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "0": "m",
     "1": "a",
     "10": "a",
     "11": "r",
     "12": "c",
     "13": "h",
     "14": "_",
     "15": "c",
     "16": "l",
     "17": "u",
     "18": "s",
     "19": "t",
     "2": "x",
     "20": "e",
     "21": "r",
     "22": "_",
     "23": "s",
     "24": "t",
     "25": "a",
     "26": "t",
     "27": "u",
     "28": "s",
     "29": "{",
     "3": "(",
     "30": "c",
     "31": "l",
     "32": "u",
     "33": "s",
     "34": "t",
     "35": "e",
     "36": "r",
     "37": "=",
     "38": "\"",
     "39": "$",
     "4": "o",
     "40": "c",
     "41": "l",
     "42": "u",
     "43": "s",
     "44": "t",
     "45": "e",
     "46": "r",
     "47": "\"",
     "48": "}",
     "49": ")",
     "5": "p",
     "6": "e",
     "7": "n",
     "8": "s",
     "9": "e",
     "expr": "max(opensearch_cluster_status{cluster=~\"$cluster\"} == 0)"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(max(opensearch_cluster_status{cluster=~\"$cluster\"}) == 0) + 1",
     "legendFormat": "GREEN"
    },
    {
     "expr": "(max(opensearch_cluster_status{cluster=~\"$cluster\"}) == 1)",
     "legendFormat": "YELLOW"
    },
    {
     "expr": "(max(opensearch_cluster_status{cluster=~\"$cluster\"}) == 2) - 1",
     "legendFormat": "RED"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(opensearch_cluster_nodes_number{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Data nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(opensearch_cluster_datanodes_number{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Pending tasks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(opensearch_cluster_pending_tasks_number{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Shards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$shard_type shards",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
     "repeat": "shard_type",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(opensearch_cluster_shards_number{cluster=~\"$cluster\",type=\"$shard_type\"})",
       "legendFormat": "$shard_type"
      }
     ]
    },
    {
     "title": "$pool_name tasks",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
     "repeat": "pool_name",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(opensearch_threadpool_tasks_number{cluster=~\"$cluster\",name=\"$pool_name\"})",
       "legendFormat": "$pool_name"
      }
     ]
    }
   ]
  },
  {
   "title": "Threadpools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "Documents and Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Documents indexing rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(sum by (node) (opensearch_indices_indexing_index_count{cluster=~\"$cluster\", node=~\"$node\"})[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Indexing latency",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 6, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (node) (rate(opensearch_indices_indexing_index_time_seconds{cluster=~\"$cluster\", node=~\"$node\"}[$interval]) / rate(opensearch_indices_indexing_index_count{cluster=~\"$cluster\", node=~\"$node\"}[$interval]))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Search rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (node) (rate(opensearch_indices_search_query_count{cluster=~\"$cluster\", node=~\"$node\"}[$interval]))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Search latency",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 18, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (node) (rate(opensearch_indices_search_query_time_seconds{cluster=~\"$cluster\", node=~\"$node\"}[$interval]) / rate(opensearch_indices_search_query_count{cluster=~\"$cluster\", node=~\"$node\"}[$interval]))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Documents count (with replicas)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (node) (opensearch_indices_doc_number{cluster=~\"$cluster\", node=~\"$node\"})",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Documents deleting rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (node) (rate(opensearch_indices_doc_deleted_number{cluster=~\"$cluster\", node=~\"$node\"}[$interval]))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Documents merging rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (node) (rate(opensearch_indices_merges_total_docs_count{cluster=~\"$cluster\",node=~\"$node\"}[$interval]))",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Field data memory size",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (node) (opensearch_indices_fielddata_memory_size_bytes{cluster=~\"$cluster\", node=~\"$node\"})",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Field data evictions",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (node) (rate(opensearch_indices_fielddata_evictions_count{cluster=~\"$cluster\", node=~\"$node\"}[$interval]))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Query cache size",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (node) (opensearch_indices_querycache_cache_size_bytes{cluster=~\"$cluster\", node=~\"$node\"})",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Query cache evictions",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 6, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (node) (rate(opensearch_indices_querycache_evictions_count{cluster=~\"$cluster\", node=~\"$node\"}[$interval]))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Query cache hits",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (node) (rate(opensearch_indices_querycache_hit_count{cluster=~\"$cluster\", node=~\"$node\"}[$interval]))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Query cache misses",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 18, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (node) (rate(opensearch_indices_querycache_miss_number{cluster=~\"$cluster\", node=~\"$node\"}[$interval]))",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Throttling",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Indexing throttling",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (node) (rate(opensearch_indices_indexing_throttle_time_seconds{cluster=~\"$cluster\", node=~\"$node\"}[$interval]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Merging throttling",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (node) (rate(opensearch_indices_merges_total_throttled_time_seconds{cluster=~\"$cluster\", node=~\"$node\"}[$interval]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Heap used",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (node) (opensearch_jvm_mem_heap_used_bytes{cluster=~\"$cluster\", node=~\"$node\"})",
     "legendFormat": "{{node}} - heap used"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (node) (rate(opensearch_jvm_gc_collection_count{cluster=~\"$cluster\",node=~\"$node\"}[$interval]))",
     "legendFormat": "{{node}} - {{gc}}"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (node) (rate(opensearch_jvm_gc_collection_time_seconds{cluster=~\"$cluster\", node=~\"$node\"}[$interval]))",
     "legendFormat": "{{node}} - {{gc}}"
    }
   ]
  }
 ]
}