{
 "title": "Varnish overview",
 "tags": [ "varnish-cache-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "DS_PROMETHEUS",
    "label": "Data Source",
    "query": "victoriametrics-metrics-datasource"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(varnish_main_sessions{job=~\"$job\"},cluster)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(varnish_main_sessions,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(varnish_main_sessions{cluster=\"$cluster\", cluster=\"$cluster\", job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cache hit rate",
   "type": "gauge",
   "description": "Rate of cache hits to misses.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((rate(varnish_main_cache_hit{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) / clamp_min(rate(varnish_main_cache_hit{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) + rate(varnish_main_cache_miss{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]), 1))) * 100\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Frontend requests",
   "type": "stat",
   "description": "The rate of requests sent to the Varnish Cache frontend.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(varnish_main_client_req{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{nstance}}"
    }
   ]
  },
  {
   "title": "Backend requests",
   "type": "stat",
   "description": "The rate of requests sent to the Varnish Cache backends.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(varnish_main_backend_req{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Sessions rate",
   "type": "stat",
   "description": "The rate of total sessions created in the Varnish Cache instance.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "/ sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(varnish_main_sessions_total{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cache hits",
   "type": "stat",
   "description": "The rate of cache hits.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "/ sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(varnish_main_cache_hit{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cache hit pass",
   "type": "stat",
   "description": "Rate of cache hits for pass objects (fulfilled requests that are not cached).",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "/ sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(varnish_main_cache_hitpass{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Session queue length",
   "type": "stat",
   "description": "Length of session queue waiting for threads.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(varnish_main_thread_queue_len{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pools",
   "type": "stat",
   "description": "Number of thread pools.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(varnish_main_pools{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Backend connections",
   "type": "timeseries",
   "description": "Rate of recycled, reused, busy, unhealthy, and accepted backend connections by Varnish Cache.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "conn/s" } },
   "targets": [
    {
     "expr": "irate(varnish_main_backend_conn{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - Accepted"
    },
    {
     "expr": "irate(varnish_main_backend_recycle{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - Recycled"
    },
    {
     "expr": "irate(varnish_main_backend_reuse{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - Reused"
    },
    {
     "expr": "irate(varnish_main_backend_busy{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - Busy"
    },
    {
     "expr": "irate(varnish_main_backend_unhealthy{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - Unhealthy"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "description": "Rate of new connected, queued, and dropped sessions.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "sess/s" } },
   "targets": [
    {
     "expr": "irate(varnish_main_sessions{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\",type=\"conn\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - Connected"
    },
    {
     "expr": "irate(varnish_main_sessions{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\",type=\"queued\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - Queued"
    },
    {
     "expr": "irate(varnish_main_sessions{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\",type=\"dropped\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - Dropped"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "Rate of frontend and backend requests received.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(varnish_main_client_req{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - Frontend"
    },
    {
     "expr": "irate(varnish_main_backend_req{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - Backend"
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "timeseries",
   "description": "Ratio of cache hits to cache misses.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (instance, job) ((rate(varnish_main_cache_hit{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) / clamp_min(rate(varnish_main_cache_hit{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) + rate(varnish_main_cache_miss{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]), 1))) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "timeseries",
   "description": "Bytes allocated from Varnish Cache storage.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "varnish_sma_c_bytes{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cache events",
   "type": "timeseries",
   "description": "Rate of expired and LRU (least recently used) nuked objects.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(varnish_main_n_expired{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - Expired"
    },
    {
     "expr": "irate(varnish_main_n_lru_nuked{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - Nuked"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "description": "Rate for the response bytes of header and body for frontend and backends.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(varnish_main_s_resp_hdrbytes{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} -  Frontend header"
    },
    {
     "expr": "irate(varnish_main_s_resp_bodybytes{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - Frontend body"
    },
    {
     "expr": "irate(varnish_backend_beresp_hdrbytes{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} -  {{backend}} - Backend header"
    },
    {
     "expr": "irate(varnish_backend_beresp_bodybytes{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} -  {{backend}} - Backend body"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "description": "Number of failed, created, limited, and current threads.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(varnish_main_threads_failed{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Failed"
    },
    {
     "expr": "increase(varnish_main_threads_created{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Created"
    },
    {
     "expr": "increase(varnish_main_threads_limited{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Limited"
    },
    {
     "expr": "varnish_main_threads{cluster=\"$cluster\", job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - Total"
    }
   ]
  }
 ]
}