{
 "title": "Blackbox Exporter (HTTP prober)",
 "description": "Blackbox exporter HTTP prober dashboard",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "DS_PROMETHEUS",
    "query": "victoriametrics-metrics-datasource"
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(probe_success,cluster)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(probe_success{cluster=\"$cluster\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(probe_success{cluster=~\"$cluster\",job=~\"$job\", cluster=\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Probe Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{cluster=~\"$cluster\",job=~\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "probe_http_ssl{cluster=~\"$cluster\",job=~\"$job\", instance=~\"$instance\"} > 0"
    },
    {
     "expr": "(probe_ssl_earliest_cert_expiry{cluster=~\"$cluster\",job=~\"$job\", instance=~\"$instance\"} - time()) / 3600 / 24"
    },
    {
     "expr": "probe_http_status_code{cluster=~\"$cluster\",job=~\"$job\", instance=~\"$instance\"} > 0"
    },
    {
     "expr": "avg_over_time(probe_duration_seconds{cluster=~\"$cluster\",job=~\"$job\", instance=~\"$instance\"}[1m])"
    },
    {
     "expr": "probe_tls_version_info{cluster=~\"$cluster\",job=~\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "avg_over_time(probe_dns_lookup_time_seconds{cluster=~\"$cluster\",job=~\"$job\", instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "HTTP Probe Duration",
   "type": "timeseries",
   "description": "Returns how long the probe took to complete in seconds",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{cluster=~\"$cluster\",job=~\"$job\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "$instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "HTTP Probe Phases Duration",
   "type": "timeseries",
   "description": "Duration of http request by phase, summed over all redirects",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{cluster=~\"$cluster\",job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  }
 ]
}