{
 "title": "Keda Operator",
 "description": "Keda Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "DS_PROMETHEUS",
    "query": "victoriametrics-metrics-datasource"
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(keda_build_info,cluster)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(keda_build_info{cluster=\"$cluster\"},job)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(keda_build_info{job=\"$job\", cluster=\"$cluster\"},version)"
    }
   },
   {
    "name": "goversion",
    "query": {
     "query": "label_values(keda_build_info{job=\"$job\", cluster=\"$cluster\"},goversion)"
    }
   },
   {
    "name": "git_commit",
    "query": {
     "query": "label_values(keda_build_info{job=\"$job\", cluster=\"$cluster\"},git_commit)"
    }
   },
   {
    "name": "goarch",
    "query": {
     "query": "label_values(keda_build_info{job=\"$job\", cluster=\"$cluster\"},goarch)"
    }
   },
   {
    "name": "goos",
    "query": {
     "query": "label_values(keda_build_info{job=\"$job\", cluster=\"$cluster\"},goos)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Scaled Objects Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (scaledObject, exported_namespace) (rate(keda_scaled_object_errors_total{cluster=~\"$cluster\",job=~\"$job\"}[2m]))",
     "legendFormat": "{{scaledObject}} - {{exported_namespace}}"
    }
   ]
  },
  {
   "title": "Resource Registred",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type, exported_namespace) (keda_resource_registered_total{cluster=~\"$cluster\",job=~\"$job\"})",
     "legendFormat": "{{type}} - {{exported_namespace}}"
    }
   ]
  },
  {
   "title": "Triggers Registered",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (keda_trigger_registered_total{cluster=~\"$cluster\",job=~\"$job\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Keda Operator Info",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "options": {
    "content": "- **Version**: `$version`\n- **Commit**: `$git_commit`\n- **Go Version**: `$goversion`\n- **Architecture**: `$goarch`\n- **Operating System**: `$goos`"
   }
  },
  { "title": "Scalers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Scaler Metrics Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "keda_scaler_metrics_value{cluster=~\"$cluster\",job=~\"$job\"}",
     "legendFormat": "{{scaledObject}} - {{exported_namespace}} - {{type}} - {{scaler}}"
    }
   ]
  },
  {
   "title": "Scaler Metrics Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "keda_scaler_metrics_latency_seconds{cluster=~\"$cluster\",job=~\"$job\"}",
     "legendFormat": "{{scaledObject}} - {{exported_namespace}} - {{type}} - {{scaler}}"
    }
   ]
  },
  {
   "title": "Active Scalers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "keda_scaler_active{cluster=~\"$cluster\",job=~\"$job\"} == 1",
     "legendFormat": "{{scaledObject}} - {{exported_namespace}} - {{type}} - {{scaler}}"
    }
   ]
  },
  {
   "title": "Scaler Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(keda_scaler_detail_errors_total{cluster=~\"$cluster\",job=~\"$job\"}[2m])",
     "legendFormat": "{{scaledObject}} - {{exported_namespace}} - {{type}} - {{scaler}}"
    }
   ]
  },
  { "title": "Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Controller Active Workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (controller) (controller_runtime_active_workers{cluster=~\"$cluster\",job=~\"$job\"})",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Controller Reconcile Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (controller) (rate(controller_runtime_reconcile_errors_total{cluster=~\"$cluster\",job=~\"$job\"}[2m]))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconcile Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum by (le, controller)(\n    rate(controller_runtime_reconcile_time_seconds_bucket{cluster=~\"$cluster\",job=~\"$job\"}[2m])\n  )\n)",
     "legendFormat": "{{controller}} - 99%"
    },
    {
     "expr": "histogram_quantile(0.95, \n  sum by (le, controller)(\n    rate(controller_runtime_reconcile_time_seconds_bucket{cluster=~\"$cluster\",job=~\"$job\"}[2m])\n  )\n)",
     "legendFormat": "{{controller}} - 95%"
    },
    {
     "expr": "histogram_quantile(0.5, \n  sum by (le, controller)(\n    rate(controller_runtime_reconcile_time_seconds_bucket{cluster=~\"$cluster\",job=~\"$job\"}[2m])\n  )\n)",
     "legendFormat": "{{controller}} - 50%"
    }
   ]
  },
  { "title": "Work Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Work Queue Adds Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(workqueue_adds_total{cluster=~\"$cluster\",job=~\"$job\"}[2m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name) (workqueue_depth{cluster=~\"$cluster\",job=~\"$job\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum by (le, name)(\n    rate(workqueue_queue_duration_seconds_bucket{cluster=~\"$cluster\",job=~\"$job\"}[2m])\n  )\n)",
     "legendFormat": "{{name}} - 99%"
    },
    {
     "expr": "histogram_quantile(0.95, \n  sum by (le, name)(\n    rate(workqueue_queue_duration_seconds_bucket{cluster=~\"$cluster\",job=~\"$job\"}[2m])\n  )\n)",
     "legendFormat": "{{name}} - 95%"
    },
    {
     "expr": "histogram_quantile(0.50, \n  sum by (le, grpc_method, grpc_service)(\n    rate(workqueue_queue_duration_seconds_bucket{cluster=~\"$cluster\",job=~\"$job\"}[2m])\n  )\n)",
     "legendFormat": "{{name}} - 50%"
    }
   ]
  },
  {
   "title": "Work Queue Retries Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(workqueue_retries_total{cluster=~\"$cluster\",job=~\"$job\"}[2m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Unfinished Work Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name) (workqueue_unfinished_work_seconds{cluster=~\"$cluster\",job=~\"$job\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Task Duration ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum by (le, name)(\n    rate(workqueue_work_duration_seconds_bucket{cluster=~\"$cluster\",job=~\"$job\"}[2m])\n  )\n)",
     "legendFormat": "{{name}} - 99%"
    },
    {
     "expr": "histogram_quantile(0.95, \n  sum by (le, name)(\n    rate(workqueue_work_duration_seconds_bucket{cluster=~\"$cluster\",job=~\"$job\"}[2m])\n  )\n)",
     "legendFormat": "{{name}} - 95%"
    },
    {
     "expr": "histogram_quantile(0.50, \n  sum by (le, grpc_method, grpc_service)(\n    rate(workqueue_work_duration_seconds_bucket{cluster=~\"$cluster\",job=~\"$job\"}[2m])\n  )\n)",
     "legendFormat": "{{name}} - 50%"
    }
   ]
  },
  {
   "title": "Internal Metricsservice GRPC Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 }
  },
  {
   "title": "Server Handled Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (grpc_code) (rate(keda_internal_metricsservice_grpc_server_handled_total{cluster=~\"$cluster\",job=~\"$job\"}[2m]))",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "Server Handling Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum by (le, grpc_method, grpc_service)(\n    rate(keda_internal_metricsservice_grpc_server_handling_seconds_bucket{cluster=~\"$cluster\",job=~\"$job\"}[2m])\n  )\n)",
     "legendFormat": "{{grpc_service}} - {{grpc_method}} - 99%"
    },
    {
     "expr": "histogram_quantile(0.95, \n  sum by (le, grpc_method, grpc_service)(\n    rate(keda_internal_metricsservice_grpc_server_handling_seconds_bucket{cluster=~\"$cluster\",job=~\"$job\"}[2m])\n  )\n)",
     "legendFormat": "{{grpc_service}} - {{grpc_method}} - 95%"
    },
    {
     "expr": "histogram_quantile(0.50, \n  sum by (le, grpc_method, grpc_service)(\n    rate(keda_internal_metricsservice_grpc_server_handling_seconds_bucket{cluster=~\"$cluster\",job=~\"$job\"}[2m])\n  )\n)",
     "legendFormat": "{{grpc_service}} - {{grpc_method}} - 50%"
    }
   ]
  },
  {
   "title": "Server Msg Received/Sent Diff",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "keda_internal_metricsservice_grpc_server_msg_received_total{cluster=~\"$cluster\",job=~\"$job\"} - keda_internal_metricsservice_grpc_server_msg_sent_total{cluster=~\"$cluster\",job=~\"$job\"}",
     "legendFormat": "{{grpc_service}} - {{grpc_method}} - {{grpc_type}}"
    }
   ]
  },
  {
   "title": "Loop Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(keda_internal_scale_loop_latency_seconds{cluster=~\"$cluster\",job=~\"$job\"}[2m])",
     "legendFormat": "{{resource}} - {{exported_namespace}} - {{type}}"
    }
   ]
  }
 ]
}